[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = [
  "python3.10 -m venv /app/.venv",
  "/app/.venv/bin/python3.10 -m ensurepip --upgrade",
  "/app/.venv/bin/pip install --upgrade pip setuptools wheel",
  "/app/.venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/app/.venv/bin/uvicorn app:app --host 0.0.0.0 --port $PORT"
