-- BetTracer Historical Data Import Script
-- Script: 003_import_historical_data
-- Description: Imports historical bets, legs, and reference items from CSV data
-- 
-- IMPORTANT: This script assumes:
-- 1. You have a user_id to assign bets to (replace 'YOUR_USER_ID' below)
-- 2. Reference items will be created first
-- 3. Main bets will be created second
-- 4. Legs will be created last with proper foreign key references
--
-- USAGE:
-- 1. Replace 'YOUR_USER_ID' with your actual user UUID
-- 2. Run this script in your Supabase SQL editor or via psql

-- ============================================================================
-- STEP 1: Create Reference Items
-- ============================================================================
-- First, we'll create all unique reference items from the data
-- Note: This uses ON CONFLICT DO NOTHING to avoid duplicates

-- Insert Responsibles
INSERT INTO reference_items (kind, name, metadata) VALUES
  ('responsible', 'Alexy Cruz', '{}'),
  ('responsible', 'Anthony Escobar', '{}')
ON CONFLICT (kind, lower(name)) DO NOTHING;

-- Insert Leagues (from legs.csv and references.csv)
INSERT INTO reference_items (kind, name, metadata) VALUES
  ('league', 'Champions League', '{}'),
  ('league', 'Europa League', '{}'),
  ('league', 'Conference League', '{}'),
  ('league', 'Premier League', '{}'),
  ('league', 'La Liga', '{}'),
  ('league', 'Serie A', '{}'),
  ('league', 'Bundesliga', '{}'),
  ('league', 'Ligue 1', '{}'),
  ('league', 'Eredivisie', '{}'),
  ('league', 'MLS', '{}'),
  ('league', 'CONCACAF Central American Cup', '{}'),
  ('league', 'CONMEBOL Sudamericana', '{}'),
  ('league', 'EFL League Two', '{}'),
  ('league', 'EFL Trophy', '{}'),
  ('league', 'Brasileirão Betano', '{}'),
  ('league', 'Liga de Expansion MX', '{}'),
  ('league', 'UEFA World Cup Qualifying', '{}'),
  ('league', 'Liga Portugal', '{}'),
  ('league', 'Süper Lig', '{}')
ON CONFLICT (kind, lower(name)) DO NOTHING;

-- Insert Teams (from legs.csv and references.csv)
-- Note: This is a comprehensive list - you may want to verify all teams are included
INSERT INTO reference_items (kind, name, metadata) VALUES
  ('team', 'Liverpool', '{}'),
  ('team', 'Real Madrid', '{}'),
  ('team', 'Manchester City', '{}'),
  ('team', 'Borussia Dortmund', '{}'),
  ('team', 'Club Brujas', '{}'),
  ('team', 'FC Barcelona', '{}'),
  ('team', 'Qarabag', '{}'),
  ('team', 'Chelsea', '{}'),
  ('team', 'Estrella Roja', '{}'),
  ('team', 'Lille', '{}'),
  ('team', 'Stuttgart', '{}'),
  ('team', 'Feyenoord', '{}'),
  ('team', 'Shkendija Tetovo', '{}'),
  ('team', 'Jagiellonia', '{}'),
  ('team', 'Seattle Sounders', '{}'),
  ('team', 'Minnesota United', '{}'),
  ('team', 'Sunderland', '{}'),
  ('team', 'Everton', '{}'),
  ('team', 'Lazio', '{}'),
  ('team', 'Cagliari', '{}'),
  ('team', 'Sassuolo', '{}'),
  ('team', 'Génova', '{}'),
  ('team', 'Elche', '{}'),
  ('team', 'Angers', '{}'),
  ('team', 'Hellas Verona', '{}'),
  ('team', 'Inter', '{}'),
  ('team', 'Valencia', '{}'),
  ('team', 'Leipzig', '{}'),
  ('team', 'Volendam', '{}'),
  ('team', 'CD Olimpia', '{}'),
  ('team', 'Alajuelense', '{}'),
  ('team', 'Atletico Lanús', '{}'),
  ('team', 'Universidad de Chile', '{}'),
  ('team', 'Los Ángeles', '{}'),
  ('team', 'Austin', '{}'),
  ('team', 'Roma', '{}'),
  ('team', 'Parma', '{}'),
  ('team', 'Calcio Como', '{}'),
  ('team', 'Eintracht Fráncfort', '{}'),
  ('team', 'Bochum', '{}'),
  ('team', 'Lecce', '{}'),
  ('team', 'Napoli', '{}'),
  ('team', 'Atalanta', '{}'),
  ('team', 'Milan', '{}'),
  ('team', 'Betis', '{}'),
  ('team', 'Atletico de Madrid', '{}'),
  ('team', 'Moreirense', '{}'),
  ('team', 'Oporto', '{}'),
  ('team', 'Gazisehir Gaziantep', '{}'),
  ('team', 'Fenerbahçe', '{}'),
  ('team', 'Juventus', '{}'),
  ('team', 'Lyon', '{}'),
  ('team', 'Strasbourg', '{}'),
  ('team', 'Mainz', '{}'),
  ('team', 'Metz', '{}'),
  ('team', 'Arsenal', '{}'),
  ('team', 'Crystal Palace', '{}'),
  ('team', 'Colonia', '{}'),
  ('team', 'Leeds United', '{}'),
  ('team', 'West Ham United', '{}'),
  ('team', 'Real Sociedad', '{}'),
  ('team', 'Sevilla', '{}'),
  ('team', 'Celta de Vigo', '{}'),
  ('team', 'Niza', '{}'),
  ('team', 'Malmo', '{}'),
  ('team', 'NK Dinamo Zagreb', '{}'),
  ('team', 'Ajax', '{}'),
  ('team', 'Bayern de Múnich', '{}'),
  ('team', 'Monaco', '{}'),
  ('team', 'Tottenham', '{}'),
  ('team', 'Sporting de Lisboa', '{}'),
  ('team', 'O. Marsella', '{}'),
  ('team', 'Slavia Prague', '{}'),
  ('team', 'Juventus', '{}'),
  ('team', 'Olympiacos', '{}'),
  ('team', 'Copenhague', '{}'),
  ('team', 'Alavés', '{}'),
  ('team', 'Getafe', '{}'),
  ('team', 'Bayer Leverkusen', '{}'),
  ('team', 'Villarreal', '{}'),
  ('team', 'Charlotte', '{}'),
  ('team', 'New York City', '{}'),
  ('team', 'Genclerbirligi', '{}'),
  ('team', 'Istanbul Basaksehir', '{}'),
  ('team', 'Paris FC', '{}'),
  ('team', 'Rennes', '{}'),
  ('team', 'Wolverhampton', '{}'),
  ('team', 'Levante', '{}'),
  ('team', 'TSG Hoffenheim', '{}'),
  ('team', 'Torino', '{}'),
  ('team', 'Rayo Vallecano', '{}'),
  ('team', 'Cheltenham Town', '{}'),
  ('team', 'Notts County', '{}'),
  ('team', 'Milton Keynes', '{}'),
  ('team', 'Swindon Town', '{}'),
  ('team', 'Arsenal Academy', '{}'),
  ('team', 'Cardiff City', '{}'),
  ('team', 'Stockport County', '{}'),
  ('team', 'Wigan', '{}'),
  ('team', 'Atletico Mineiro', '{}'),
  ('team', 'Fortaleza', '{}'),
  ('team', 'Mineros de Zacatecas', '{}'),
  ('team', 'Irapuato FC', '{}'),
  ('team', 'Azerbaiyán', '{}'),
  ('team', 'Islandia', '{}'),
  ('team', 'Andorra', '{}'),
  ('team', 'Albania', '{}'),
  ('team', 'Moldavia', '{}'),
  ('team', 'Italia', '{}'),
  ('team', 'Finlandia', '{}'),
  ('team', 'Malta', '{}'),
  ('team', 'Gibraltar', '{}'),
  ('team', 'Montenegro', '{}'),
  ('team', 'Polonia', '{}'),
  ('team', 'Holanda', '{}'),
  ('team', 'Luxemburgo', '{}'),
  ('team', 'Alemania', '{}'),
  ('team', 'Suiza', '{}'),
  ('team', 'Suecia', '{}'),
  ('team', 'Chipre', '{}'),
  ('team', 'Austria', '{}'),
  ('team', 'Kazajistan', '{}'),
  ('team', 'Belgica', '{}'),
  ('team', 'Georgia', '{}'),
  ('team', 'España', '{}'),
  ('team', 'Ucrania', '{}'),
  ('team', 'Hungria', '{}'),
  ('team', 'Irlanda', '{}'),
  ('team', 'Noruega', '{}')
ON CONFLICT (kind, lower(name)) DO NOTHING;

-- Insert Bet Types (from legs.csv and references.csv)
INSERT INTO reference_items (kind, name, metadata) VALUES
  ('bet_type', 'Match Goals', '{}'),
  ('bet_type', 'Player Shots', '{}'),
  ('bet_type', 'Both Teams To Score', '{}'),
  ('bet_type', 'Double Opportunity', '{}'),
  ('bet_type', 'Team Win', '{}'),
  ('bet_type', 'Team Goals', '{}'),
  ('bet_type', 'Match Cards', '{}'),
  ('bet_type', 'Match Corners', '{}'),
  ('bet_type', 'Team Cards', '{}'),
  ('bet_type', 'Team Shots', '{}'),
  ('bet_type', 'Player Goal/Assist', '{}'),
  ('bet_type', 'Team Qualify', '{}')
ON CONFLICT (kind, lower(name)) DO NOTHING;

-- Insert Categories (from legs.csv - these are the actual bet selections)
INSERT INTO reference_items (kind, name, metadata) VALUES
  ('category', 'Over 2.5 Goals', '{}'),
  ('category', 'Kylian Mbappe: 2+ Shots On Target', '{}'),
  ('category', 'Both Teams To Score', '{}'),
  ('category', 'Manchester City or Draw', '{}'),
  ('category', 'Over 1.5 Goals', '{}'),
  ('category', 'FC Barcelona or Draw', '{}'),
  ('category', 'Over 2.5 Goals', '{}'),
  ('category', 'Lille or Draw', '{}'),
  ('category', 'Jagiellonia or Draw', '{}'),
  ('category', 'Seattle Sounders', '{}'),
  ('category', 'Under 3.5 Goals', '{}'),
  ('category', 'Under 10.5 Corners', '{}'),
  ('category', 'Over 1.5 Goals', '{}'),
  ('category', 'Lazio or Draw', '{}'),
  ('category', 'Sassuolo or Draw', '{}'),
  ('category', 'FC Barcelona', '{}'),
  ('category', 'Lille', '{}'),
  ('category', 'Inter', '{}'),
  ('category', 'Real Madrid', '{}'),
  ('category', 'Feyenoord', '{}'),
  ('category', 'Getafe or Draw', '{}'),
  ('category', 'Borussia Dortmund or Draw', '{}'),
  ('category', 'PSV Eindhoven', '{}'),
  ('category', 'CD Olimpia or Draw', '{}'),
  ('category', 'CD Olimpia To Qualify', '{}'),
  ('category', 'Atletico Lanús or Draw', '{}'),
  ('category', 'Under 5.5 Cards', '{}'),
  ('category', 'Over 2.5 Cards', '{}'),
  ('category', 'Augsburg or Draw', '{}'),
  ('category', 'Napoli or Draw', '{}'),
  ('category', 'Fenerbahçe or Draw', '{}'),
  ('category', 'Juventus: 3+ Shots On Target', '{}'),
  ('category', 'Stuttgart or Draw', '{}'),
  ('category', 'Arsenal or Draw', '{}'),
  ('category', 'Kylian Mbappe: Goal or Assist', '{}'),
  ('category', 'Chelsea: Over 1.5 Cards', '{}'),
  ('category', 'Borussia Dortmund', '{}'),
  ('category', 'West Ham United: Over 0.5 Goals', '{}'),
  ('category', 'West Ham United: 3+ Shots On Target', '{}'),
  ('category', 'Malmo', '{}'),
  ('category', 'Chelsea', '{}'),
  ('category', 'Bayern de Múnich', '{}'),
  ('category', 'Monaco', '{}'),
  ('category', 'Atalanta or Draw', '{}'),
  ('category', 'Real Madrid', '{}'),
  ('category', 'Eintracht Fráncfort', '{}'),
  ('category', 'Real Madrid: Over 1.5 Goals', '{}'),
  ('category', 'Copenhague', '{}'),
  ('category', 'Brentford: Over 0.5 Goals', '{}'),
  ('category', 'Under 7.5 Cards', '{}'),
  ('category', 'Manchester United: 3+ Shots On Target', '{}'),
  ('category', 'Bayer Leverkusen or Draw', '{}'),
  ('category', 'Betis: Over 0.5 Goals', '{}'),
  ('category', 'New York City or Draw', '{}'),
  ('category', 'Istanbul Basaksehir or Draw', '{}'),
  ('category', 'Tottenham', '{}'),
  ('category', 'Manchester United', '{}'),
  ('category', 'Atletico de Madrid', '{}'),
  ('category', 'Juventus', '{}'),
  ('category', 'Rayo Vallecano', '{}'),
  ('category', 'FC Barcelona', '{}'),
  ('category', 'Cheltenham Town or Notts County', '{}'),
  ('category', 'Cardiff City', '{}'),
  ('category', 'Atletico Mineiro', '{}'),
  ('category', 'Mineros de Zacatecas', '{}'),
  ('category', 'Azerbaiyán', '{}'),
  ('category', 'Albania', '{}'),
  ('category', 'Moldavia', '{}'),
  ('category', 'Finlandia', '{}'),
  ('category', 'Gibraltar', '{}'),
  ('category', 'Polonia', '{}'),
  ('category', 'Luxemburgo', '{}'),
  ('category', 'Suiza or Draw', '{}'),
  ('category', 'Chipre', '{}'),
  ('category', 'Kazajistan', '{}'),
  ('category', 'Georgia', '{}'),
  ('category', 'Ucrania', '{}'),
  ('category', 'Hungria', '{}'),
  ('category', 'Italia', '{}')
ON CONFLICT (kind, lower(name)) DO NOTHING;

-- ============================================================================
-- NOTE: The actual import of main bets and legs should be done via a script
-- that parses the CSV files and inserts the data with proper foreign keys.
-- This SQL file creates the reference items, but you'll need to:
-- 1. Parse mainBets.csv to create main_bets records
-- 2. Parse legs.csv to create legs records with proper FK references
-- 3. Map the "Responsible" field to user_id (you may need multiple users)
--
-- See the Python/Node.js import script for the full implementation.
-- ============================================================================

